### ISSUE TITLE
Writing docs for this library and have some exploratory questions

### ISSUE THREAD

**Issue by JohnAD** [status-im/nim-faststreams#7]
I'm writing general docs for this library. I'm both writing inline comments and general docs. I might even do a YouTube video.

You can see it stubbed out a bit at my fork: https://github.com/JohnAD/nim-faststreams

I see in `input_streams` that there appears to be two general means of handling input:

1. using `memFile` and `openFile`. The result of this is generally limited to doing a `readBytes`.

2. using `init` to create a possibly distinct-typed `ByteStream`. This gives you considerable control over the cursor, but getting data is limited to one byte at a time. I get the impression it is more of a tool box, but I'm unable to find examples of it's use.

What are the thoughts about this separation? I suspect I'm missing something. :)

In `output_streams` I see that reading from a file is not possible yet; a comment says that it is waiting on a later nim version. Given that nim is well over 1.0 now, is this safe to debug and restore to service? Would moving the .nimble file `requires` above 0.17.0 cause havoc in other projects?

**Comment by zah** [comment]
Hi @JohnAD,

Thank you for your effort to document the library. I'll be happy to help you along with this, although I don't consider the API of the library to be finalised. One of my major goals is to add an async aspect to the API and I guess I need to scale back the weird mixed usage of `ref` and `var` in the public interface. The intention there is to make it easier for me to track the parts of the library that can become more optimal in a possible future version of Nim, but since the whole library is small enough, I can just addrses this when the time comes and make the library as pleasant to use as possible now.

Would you like to chat on Gitter regarding the planned changes to the library? At Status, we actually have a feature bounty program where external developers like you can get some funding to improve our libraries:

https://forum.nim-lang.org/t/6007

**Comment by zah** [comment]
I'm in Europe (UTC +0300), but we have some overlapping hours in the mornings. I hope you enjoy conversations about Nim after breakfast :) Anyway, I've messaged you on Gitter, let's continue there.

**Comment by JohnAD** [comment]
Sorry about the delay in me writing docs. My time got sucked into finishing the first part of a nim decimal library (it uses IEEE 754 20008 standard for 128-bit decimals.)

I see the expanded README doc you placed into the `post-review-fixes` branch. **Looks good!**

I might limit myself to a few tweaks and perhaps a YouTube explainer video.

**Comment by zah** [comment]
The README of the library now provides relatively comprehenstive documentation.
