### ISSUE TITLE
Does Nim requirement have to be >=1.2?

### ISSUE THREAD

**Issue by narimiran** [status-im/nim-faststreams#9]
Similar to https://github.com/status-im/nim-stew/issues/32:

Is it possible for this package to use Nim >=1.0, or is `requires "nim >= 1.2"` necessary?

I'm asking because this package is used by your https://github.com/status-im/nim-chronicles — making that package now fail with Nim 1.0.x CIs.

**Comment by zah** [comment]
This package already requires Nim 1.2:
https://github.com/status-im/nim-faststreams/blob/master/faststreams.nimble#L10

**Comment by narimiran** [comment]
> This package already requires Nim 1.2:

I think you misunderstood my question.

Yes, it requires v1.2.x, but I'm wondering if you can lower your requirements to v1.0.x, so package(s) which rely on it can continue to work with Nim v1.0.x.

**Comment by zah** [comment]
I don't think so. I want to take advantage of fixes brought by Nim 1.2

**Comment by narimiran** [comment]
Ok, then we will disable testing Chronicles with Nim 1.0.x.

How about Stew? https://github.com/status-im/nim-stew/issues/32

**Comment by arnetheduck** [comment]
@narimiran if things break because we set a version requirement on one of the packages (like `>= 1.2`) the ideal would be that the Nim tests use the latest version that doesn't require the new nim version.

We generally work with only one Nim version, but that doesn't mean that older versions of our code cease to work with older versions of Nim.

**Comment by arnetheduck** [comment]
The same goes for stew - the commit before we set `>= 1.2` should continue to work with the 1.0 series - if it helps we can probably tag it somehow
